volumes:
  shared-workspace:
    name: "distributed-filesystem"
    driver: local

services:
  jupyterlab:
    image: jupyterlab
    volumes:
      - shared-workspace:/opt/workspace
    ports:
      - 8888:8888

  spark-master:
    image: spark-base
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - shared-workspace:/opt/workspace
    env_file:
      - spark.env
    ports:
      - 9090:8080
      - 7077:7077

  spark-history-server:
    image: spark-base
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    volumes:
      - shared-workspace:/opt/workspace
      - shared-workspace:/opt/spark/spark-events
    env_file:
      - spark.env
    ports:
      - 18080:18080


  spark-worker:
    image: spark-base
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    volumes:
      - shared-workspace:/opt/workspace
    env_file:
      - spark.env
